version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "17:30"
    timezone: Europe/London
  ignore:
  - dependency-name: phar-io/version
    versions:
    - 3.1.0
  - dependency-name: psr/container
    versions:
    - 1.1.0
    - 1.1.1
  - dependency-name: behat/gherkin
    versions:
    - 4.8.0
  - dependency-name: symfony/console
    versions:
    - 5.2.3
  - dependency-name: symfony/css-selector
    versions:
    - 5.2.3
  - dependency-name: symfony/string
    versions:
    - 5.2.3
  - dependency-name: symfony/finder
    versions:
    - 5.2.3
  - dependency-name: symfony/event-dispatcher
    versions:
    - 5.2.3
