language: php

dist: trusty

sudo: false

branches:
  only:
    - master
    - /^(?:(\d+)\.)?(?:(\d+)\.)?(\*|\d+)$/

cache:
  directories:
    - $HOME/.composer/cache/files

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

env:
  global:
    - COMPOSER_NO_INTERACTION=1

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_install:
  # Disable xDebug to speed up the build unless test coverage is needed
  - if [[ $(phpenv version-name) != "nightly" ]]; then phpenv config-rm xdebug.ini; fi

install:
  - travis_retry composer install --prefer-dist --no-suggest

script:
  - composer test
